name: Upload File

on:
  schedule:
    - cron: '15 22 * * *' # רץ בשעה 22:15 (22:15 UTC) כל יום
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install PyGithub

      - name: Upload file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python upload_file.py
